
(async()=>{
const K='today-os-m3',K2='today-os-m2',K1='today-os-m1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const uid=()=>Math.random().toString(36).slice(2,9)+Date.now().toString(36).slice(-5);
const iso=(d=new Date())=>{const x=new Date(d);x.setHours(12,0,0,0);return x.toISOString().slice(0,10)};
const add=(n,b=new Date())=>{const d=new Date(b);d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return iso(d)};
const fmt=(s,o={month:'short',day:'numeric'})=>s?new Date(s+'T12:00:00').toLocaleDateString('en-US',o):'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const seed={items:[
{id:uid(),type:'task',title:'Review roadmap priorities',dueDate:iso(),priority:'urgent',project:'Work',person:'',notes:'',completed:false,archived:false,createdAt:Date.now(),repeat:'none',history:[]},
{id:uid(),type:'meeting',title:'Product review',dueDate:iso(),time:'16:00',priority:'normal',project:'Work',person:'',notes:'',completed:false,archived:false,createdAt:Date.now(),repeat:'none',history:[]},
{id:uid(),type:'waiting',title:'Follow up with Taek',dueDate:add(2),priority:'normal',project:'Haven',person:'Taek',notes:'Next interview step.',completed:false,archived:false,createdAt:Date.now(),repeat:'none',history:[]},
{id:uid(),type:'note',title:'Haven positioning ideas',dueDate:'',priority:'normal',project:'Haven',person:'',notes:'Connect delivery leadership with digital health outcomes.',completed:false,archived:false,createdAt:Date.now(),repeat:'none',history:[]}
],projects:[{id:uid(),name:'Work',description:'Professional priorities'},{id:uid(),name:'Haven',description:'Interview process'},{id:uid(),name:'Personal',description:'Personal life'}],view:'today',selectedDate:iso(),theme:'linear',activeProject:'',activePerson:''};
const DB_NAME='today-os-db',DB_VERSION=1,STATE_STORE='app_state',STATE_ID='current';
let state=structuredClone(seed),expanded=new Set(),focus=null,timer=25*60,timerRun=false,timerInt=null,dbPromise=null,saveChain=Promise.resolve();
function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STATE_STORE))db.createObjectStore(STATE_STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
function normalize(p){const items=(p?.items||[]).map(i=>({person:'',repeat:'none',history:[],...i}));return{...structuredClone(seed),...(p||{}),items,projects:p?.projects||seed.projects,view:p?.view||'today',theme:p?.theme||'linear',activeProject:p?.activeProject||'',activePerson:p?.activePerson||''}}
async function load(){try{const db=await openDB();const stored=await new Promise((resolve,reject)=>{const tx=db.transaction(STATE_STORE,'readonly');const req=tx.objectStore(STATE_STORE).get(STATE_ID);req.onsuccess=()=>resolve(req.result?.value||null);req.onerror=()=>reject(req.error)});if(stored)return normalize(stored);const raw=localStorage.getItem(K)||localStorage.getItem(K2)||localStorage.getItem(K1);const migrated=raw?normalize(JSON.parse(raw)):structuredClone(seed);await writeState(migrated);if(raw)localStorage.setItem('today-os-indexeddb-migrated-at',new Date().toISOString());return migrated}catch(err){console.error('IndexedDB load failed',err);try{const raw=localStorage.getItem(K)||localStorage.getItem(K2)||localStorage.getItem(K1);return raw?normalize(JSON.parse(raw)):structuredClone(seed)}catch{return structuredClone(seed)}}}
async function writeState(value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STATE_STORE,'readwrite');tx.objectStore(STATE_STORE).put({id:STATE_ID,value,updatedAt:Date.now()});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
function save(){const snapshot=structuredClone(state);saveChain=saveChain.then(()=>writeState(snapshot)).catch(err=>{console.error('IndexedDB save failed',err);toast('Storage error')});return saveChain}
async function requestPersistentStorage(){try{if(navigator.storage?.persist){const granted=await navigator.storage.persist();return granted}}catch{}return false}
async function storageInfo(){try{const estimate=await navigator.storage?.estimate?.();const persisted=await navigator.storage?.persisted?.();return{persisted:!!persisted,usage:estimate?.usage||0,quota:estimate?.quota||0}}catch{return{persisted:false,usage:0,quota:0}}}
function active(){return state.items.filter(i=>!i.archived)}
function parseDate(t){const l=t.toLowerCase();if(/\btoday\b/.test(l))return iso();if(/\btomorrow\b/.test(l))return add(1);if(/\bnext week\b/.test(l))return add(7);let m=l.match(/\bin (\d+) days?\b/);if(m)return add(+m[1]);const days=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];for(let i=0;i<7;i++)if(l.includes(days[i])){const d=new Date();let n=(i-d.getDay()+7)%7||7;return add(n)}m=l.match(/\b20\d\d-\d\d-\d\d\b/);return m?m[0]:''}
function parseTime(t){const m=t.match(/\b([01]?\d|2[0-3])(?::([0-5]\d))?\s*(am|pm)?\b/i);if(!m)return'';let h=+m[1];if(m[3]?.toLowerCase()==='pm'&&h<12)h+=12;if(m[3]?.toLowerCase()==='am'&&h===12)h=0;return String(h).padStart(2,'0')+':'+(m[2]||'00')}
function parse(raw){let text=raw.trim(),type='task',priority='normal';if(/^!/.test(text)){priority='urgent';text=text.replace(/^!(urgent|important)?\s*/i,'')}if(/^waiting( for)?\b/i.test(text)){type='waiting';text=text.replace(/^waiting( for)?\s*/i,'')}else if(/^(meeting|meet)\b/i.test(text)){type='meeting';text=text.replace(/^(meeting|meet)\s*/i,'')}else if(/^note\b/i.test(text)){type='note';text=text.replace(/^note\s*/i,'')}else if(/^idea\b/i.test(text)){type='idea';text=text.replace(/^idea\s*/i,'')}const project=(text.match(/#([\w-]+)/)||[])[1]||'';const person=(text.match(/@([\w-]+)/)||[])[1]||'';let repeat='none';if(/every weekday/i.test(text))repeat='weekday';else if(/every (\d+) weeks?/i.test(text))repeat='weeks:'+RegExp.$1;else if(/first monday/i.test(text))repeat='firstMonday';else if(/last friday/i.test(text))repeat='lastFriday';else if(/daily|every day/i.test(text))repeat='daily';else if(/weekly|every week/i.test(text))repeat='weekly';else if(/monthly|every month/i.test(text))repeat='monthly';const dueDate=parseDate(text)||(type==='task'?iso():'');const time=type==='meeting'?parseTime(text):'';text=text.replace(/#[\w-]+|@[\w-]+/g,'').replace(/\b(today|tomorrow|next week|sunday|monday|tuesday|wednesday|thursday|friday|saturday)\b/ig,'').replace(/\bin \d+ days?\b/ig,'').replace(/\b(every weekday|every \d+ weeks?|first monday|last friday|daily|every day|weekly|every week|monthly|every month)\b/ig,'').replace(/\b([01]?\d|2[0-3])(?::[0-5]\d)?\s*(am|pm)?\b/ig,'').replace(/\s{2,}/g,' ').trim();return{type,title:text||'Untitled',priority,project,person,dueDate,time,repeat}}
function addItem(text){if(!text.trim())return;const p=parse(text);state.items.unshift({id:uid(),...p,notes:'',completed:false,archived:false,createdAt:Date.now(),history:[{at:Date.now(),action:'created'}]});if(p.project&&!state.projects.some(x=>x.name.toLowerCase()===p.project.toLowerCase()))state.projects.push({id:uid(),name:p.project,description:''});save();render();toast('Captured')}
function nextDate(i){let d=new Date((i.dueDate||iso())+'T12:00:00');const r=i.repeat;if(r==='daily')d.setDate(d.getDate()+1);if(r==='weekly')d.setDate(d.getDate()+7);if(r==='monthly')d.setMonth(d.getMonth()+1);if(r==='weekday'){do d.setDate(d.getDate()+1);while([0,6].includes(d.getDay()))}if(r.startsWith('weeks:'))d.setDate(d.getDate()+7*Number(r.split(':')[1]));if(r==='firstMonday'){d.setMonth(d.getMonth()+1,1);while(d.getDay()!==1)d.setDate(d.getDate()+1)}if(r==='lastFriday'){d.setMonth(d.getMonth()+2,0);while(d.getDay()!==5)d.setDate(d.getDate()-1)}return iso(d)}
function complete(id){const i=state.items.find(x=>x.id===id);if(!i)return;i.completed=!i.completed;i.completedAt=i.completed?iso():'';i.history=[...(i.history||[]),{at:Date.now(),action:i.completed?'completed':'reopened'}];if(i.completed&&i.repeat&&i.repeat!=='none')state.items.unshift({...i,id:uid(),completed:false,completedAt:'',dueDate:nextDate(i),createdAt:Date.now(),history:[{at:Date.now(),action:'recurrence created'}]});save();render()}
function update(id,p){const i=state.items.find(x=>x.id===id);if(!i)return;Object.assign(i,p);i.history=[...(i.history||[]),{at:Date.now(),action:'updated'}];save();render()}
function suggestions(){const a=active(),out=[];const overdue=a.filter(i=>!i.completed&&i.dueDate&&i.dueDate<iso());if(overdue.length)out.push({icon:'↗',text:`Review ${overdue.length} overdue item${overdue.length>1?'s':''}`,action:'timeline'});const waiting=a.filter(i=>i.type==='waiting'&&!i.completed&&i.dueDate&&i.dueDate<=add(2));if(waiting.length)out.push({icon:'@',text:`Follow up with ${waiting[0].person||waiting[0].title}`,jump:waiting[0].id});const stale=state.projects.find(p=>{const its=a.filter(i=>i.project===p.name);return its.length&&Math.max(...its.map(i=>i.createdAt||0))<Date.now()-7*864e5});if(stale)out.push({icon:'◇',text:`${stale.name} has been quiet for over a week`,project:stale.name});if(!out.length)out.push({icon:'✓',text:'Everything looks under control today.'});return out.slice(0,3)}
function metrics(){const a=active();return{urgent:a.filter(i=>!i.completed&&i.priority==='urgent').length,today:a.filter(i=>!i.completed&&i.dueDate===iso()).length,meetings:a.filter(i=>!i.completed&&i.type==='meeting'&&i.dueDate===iso()).length,waiting:a.filter(i=>!i.completed&&i.type==='waiting').length,overdue:a.filter(i=>!i.completed&&i.dueDate&&i.dueDate<iso()).length}}
function itemHTML(i){return `<div class="entity ${i.completed?'completed':''} ${expanded.has(i.id)?'expanded':''}" id="e-${i.id}"><div class="entity-row"><button class="check" data-complete="${i.id}">✓</button><div><div class="title" data-expand="${i.id}">${esc(i.title)}</div><div class="meta">${i.project?`<span class="tag">${esc(i.project)}</span>`:''}${i.person?`<span>@${esc(i.person)}</span>`:''}${i.dueDate?`<span>${fmt(i.dueDate)}${i.time?' · '+i.time:''}</span>`:''}<span>${esc(i.type)}</span>${i.priority==='urgent'?'<span class="tag urgent">urgent</span>':''}${i.repeat&&i.repeat!=='none'?`<span>↻ ${esc(i.repeat)}</span>`:''}</div></div><div class="actions"><button data-star="${i.id}">◆</button><button data-focus="${i.id}">◎</button><button data-expand="${i.id}">•••</button></div></div><div class="details"><div class="grid"><div class="field"><label>Title</label><input data-edit="${i.id}" data-field="title" value="${esc(i.title)}"></div><div class="field"><label>Type</label><select data-edit="${i.id}" data-field="type">${['task','meeting','waiting','note','idea'].map(x=>`<option ${i.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Due</label><input type="date" data-edit="${i.id}" data-field="dueDate" value="${esc(i.dueDate||'')}"></div><div class="field"><label>Time</label><input type="time" data-edit="${i.id}" data-field="time" value="${esc(i.time||'')}"></div><div class="field"><label>Project</label><input data-edit="${i.id}" data-field="project" value="${esc(i.project||'')}"></div><div class="field"><label>Person</label><input data-edit="${i.id}" data-field="person" value="${esc(i.person||'')}"></div><div class="field"><label>Repeat</label><select data-edit="${i.id}" data-field="repeat">${['none','daily','weekday','weekly','monthly','firstMonday','lastFriday','weeks:2','weeks:3'].map(x=>`<option value="${x}" ${i.repeat===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select data-edit="${i.id}" data-field="priority"><option value="normal">normal</option><option value="urgent" ${i.priority==='urgent'?'selected':''}>urgent</option></select></div><div class="field wide"><label>Notes</label><textarea data-edit="${i.id}" data-field="notes">${esc(i.notes||'')}</textarea></div></div><div style="margin-top:9px"><button class="btn" data-archive="${i.id}">Archive</button></div></div></div>`}
function section(title,items,placeholder='Add item...'){return `<section class="section"><div class="section-head"><span class="section-title">${title}</span><span class="tag">${items.length}</span></div><div class="inline-add"><span>+</span><input data-add placeholder="${placeholder}"></div>${items.length?items.map(itemHTML).join(''):'<div class="empty">Nothing here.</div>'}</section>`}
function todayView(){const m=metrics(),a=active();const items=a.filter(i=>!i.archived&&(!i.completed)&&(i.dueDate===iso()||i.priority==='urgent')).sort((x,y)=>(y.priority==='urgent')-(x.priority==='urgent'));return `<div class="brief"><div class="brief-head"><div class="eyebrow">Daily Brief</div><h2>${greeting()}, Rodrigo.</h2></div><div class="brief-grid"><div class="metric"><strong>${m.today}</strong><span>due today</span></div><div class="metric"><strong>${m.urgent}</strong><span>urgent</span></div><div class="metric"><strong>${m.meetings}</strong><span>meetings</span></div><div class="metric"><strong>${m.overdue}</strong><span>overdue</span></div></div></div><div class="suggestions"><div class="section-head"><span class="section-title">Smart Suggestions</span></div>${suggestions().map(s=>`<div class="suggestion" ${s.jump?`data-jump="${s.jump}"`:s.action?`data-view="${s.action}"`:s.project?`data-project="${s.project}"`:''}><span class="suggestion-icon">${s.icon}</span><span>${esc(s.text)}</span><span>→</span></div>`).join('')}</div>${section('Today + Must Remember',items,'Capture for today...')}`}
function greeting(){const h=new Date().getHours();return h<12?'Good morning':h<18?'Good afternoon':'Good evening'}
function timelineView(){const groups={};active().filter(i=>!i.archived).forEach(i=>{const k=i.dueDate||'Unscheduled';(groups[k]??=[]).push(i)});const keys=Object.keys(groups).sort((a,b)=>a==='Unscheduled'?1:b==='Unscheduled'?-1:a.localeCompare(b));return `<section class="section"><div class="section-head"><span class="section-title">Timeline</span></div><div style="padding:16px">${keys.length?`<div class="timeline">${keys.map(k=>`<div class="timeline-group"><div class="timeline-date">${k==='Unscheduled'?k:fmt(k,{weekday:'long',month:'long',day:'numeric'})}</div>${groups[k].sort((a,b)=>(a.time||'').localeCompare(b.time||'')).map(i=>`<div class="timeline-row" data-jump="${i.id}"><span>${i.time?`<span class="tag">${i.time}</span> `:''}${esc(i.title)}</span><span class="meta">${esc(i.type)}${i.project?' · '+esc(i.project):''}</span></div>`).join('')}</div>`).join('')}</div>`:'<div class="empty">No timeline items.</div>'}</div></section>`}
function calendarView(){const d=new Date(state.selectedDate+'T12:00:00'),start=new Date(d.getFullYear(),d.getMonth(),1);start.setDate(start.getDate()-((start.getDay()+6)%7));const days=Array.from({length:42},(_,n)=>{const x=new Date(start);x.setDate(start.getDate()+n);return iso(x)});const agenda=active().filter(i=>i.dueDate===state.selectedDate);return `<section class="section"><div class="section-head"><span class="section-title">Calendar · ${fmt(state.selectedDate,{month:'long',year:'numeric'})}</span><div><button class="btn" data-cal="prev">←</button> <button class="btn" data-cal="today">Today</button> <button class="btn" data-cal="next">→</button></div></div><div style="padding:12px"><div class="calendar">${days.map(x=>{const count=active().filter(i=>i.dueDate===x&&!i.completed).length;return `<div class="day ${x===iso()?'today':''} ${x===state.selectedDate?'selected':''}" draggable="true" data-day="${x}"><div class="day-name">${new Date(x+'T12:00:00').toLocaleDateString('en-US',{weekday:'short'})}</div><div class="day-num">${new Date(x+'T12:00:00').getDate()}</div>${Array.from({length:Math.min(count,4)},()=>'<div class="day-dot"></div>').join('')}</div>`}).join('')}</div></div></section>${section(fmt(state.selectedDate,{weekday:'long',month:'long',day:'numeric'}),agenda,'Add to selected day...')}`}
function projectsView(){if(state.activeProject)return projectWorkspace(state.activeProject);const a=active();return `<div class="project-grid">${state.projects.map(p=>{const its=a.filter(i=>(i.project||'').toLowerCase()===p.name.toLowerCase()),done=its.filter(i=>i.completed).length,pct=its.length?Math.round(done/its.length*100):0;return `<div class="project-card" data-project="${esc(p.name)}"><div class="project-head"><span class="project-name">${esc(p.name)}</span><span>→</span></div><div class="project-meta">${its.length-done} open · ${its.filter(i=>i.priority==='urgent'&&!i.completed).length} urgent</div><div class="progress"><span style="width:${pct}%"></span></div></div>`}).join('')}<div class="project-card" data-new-project><div class="project-name">+ New project</div><div class="project-meta">Create a workspace</div></div></div>`}
function projectWorkspace(name){const its=active().filter(i=>(i.project||'').toLowerCase()===name.toLowerCase()),open=its.filter(i=>!i.completed),notes=its.filter(i=>['note','idea'].includes(i.type)),people=[...new Set(its.map(i=>i.person).filter(Boolean))];return `<div style="margin-bottom:10px"><button class="btn" data-back-projects>← All projects</button></div><div class="workspace"><aside class="workspace-side"><div class="eyebrow">Project</div><h2>${esc(name)}</h2><div class="workspace-stat"><b>${open.length}</b>open items</div><div class="workspace-stat"><b>${notes.length}</b>notes & ideas</div><div class="workspace-stat"><b>${people.length}</b>people</div></aside><main class="workspace-main"><div class="section-head"><span class="section-title">Project workspace</span></div><div class="inline-add"><span>+</span><input data-project-add="${esc(name)}" placeholder="Capture into ${esc(name)}..."></div>${its.length?its.map(itemHTML).join(''):'<div class="empty">No linked entities.</div>'}</main></div>`}
function peopleView(){const a=active(),names=[...new Set(a.map(i=>i.person).filter(Boolean))];if(state.activePerson){const its=a.filter(i=>i.person===state.activePerson);return `<button class="btn" data-back-people>← All people</button>${section(state.activePerson,its,`Add something involving ${state.activePerson}...`)}`}return names.length?`<div class="people-grid">${names.map(n=>{const its=a.filter(i=>i.person===n);return `<div class="person-card" data-person="${esc(n)}"><div class="person-row"><div class="avatar">${esc(n.slice(0,2).toUpperCase())}</div><div><div class="project-name">${esc(n)}</div><div class="person-meta">${its.filter(i=>!i.completed).length} open · ${its.filter(i=>i.type==='meeting').length} meetings</div></div></div></div>`}).join('')}</div>`:'<section class="section"><div class="empty">Use @Name in capture to create people relationships.</div></section>'}
function notesView(){return section('Notes & Ideas',active().filter(i=>['note','idea'].includes(i.type)),'note Capture an idea #Project @Person')}
function archiveView(){return section('Archive',state.items.filter(i=>i.archived))}
function render(){document.documentElement.dataset.theme=state.theme;const m=metrics();$('#app').innerHTML=`<div class="app"><main class="shell"><div class="topbar"><div class="row"><div class="brand"><div class="logo">OS</div><div><h1>Today OS</h1><small>Personal operating system · M3</small></div></div><div class="nav">${['today','timeline','calendar','projects','people','notes','archive'].map(v=>`<button data-view="${v}" class="${state.view===v?'active':''}">${v}</button>`).join('')}</div><div class="row"><button class="icon-btn" data-action="theme">◐</button><button class="icon-btn" data-action="palette">⌘K</button></div></div><div class="command"><span class="command-mark">⌘</span><input id="capture" placeholder="Type anything…  ! urgent · #Project · @Person"><span class="kbd">Enter</span></div><div class="stats"><span><b>${m.urgent}</b> urgent</span> · <span><b>${m.today}</b> today</span> · <span><b>${m.meetings}</b> meetings</span> · <span><b>${m.waiting}</b> waiting</span></div></div><div class="content"><div class="view active">${state.view==='today'?todayView():state.view==='timeline'?timelineView():state.view==='calendar'?calendarView():state.view==='projects'?projectsView():state.view==='people'?peopleView():state.view==='notes'?notesView():archiveView()}</div></div></main></div>${overlays()}<div class="toast" id="toast"></div>`;bind()}
function overlays(){return `<div class="palette-overlay" id="palette"><div class="palette"><input id="paletteInput" placeholder="Search or run a command…"><div class="palette-results" id="paletteResults"></div></div></div><div class="modal-overlay" id="themeModal"><div class="modal"><h3>Choose theme</h3><div class="theme-grid">${['linear','github','raycast','terminal'].map(t=>`<button class="theme-choice" data-theme-choice="${t}">${t}</button>`).join('')}</div></div></div><div class="focus-overlay" id="focus"><div class="focus"><div class="eyebrow">Current Focus</div><div class="focus-title" id="focusTitle"></div><div class="timer" id="timer">25:00</div><div class="focus-actions"><button class="btn" data-action="timer">Start</button><button class="btn" data-action="focusDone">Done</button><button class="btn" data-action="focusClose">Close</button></div></div></div>`}
function bind(){const c=$('#capture');c?.addEventListener('keydown',e=>{if(e.key==='Enter'){addItem(c.value);c.value=''}});$$('[data-view]').forEach(x=>x.onclick=()=>{state.view=x.dataset.view;state.activeProject='';state.activePerson='';save();render()});$$('[data-complete]').forEach(x=>x.onclick=()=>complete(x.dataset.complete));$$('[data-star]').forEach(x=>x.onclick=()=>{const i=state.items.find(i=>i.id===x.dataset.star);update(i.id,{priority:i.priority==='urgent'?'normal':'urgent'})});$$('[data-expand]').forEach(x=>x.onclick=()=>{const id=x.dataset.expand;expanded.has(id)?expanded.delete(id):expanded.add(id);render()});$$('[data-edit]').forEach(x=>x.onchange=()=>update(x.dataset.edit,{[x.dataset.field]:x.value}));$$('[data-archive]').forEach(x=>x.onclick=()=>update(x.dataset.archive,{archived:true}));$$('[data-focus]').forEach(x=>x.onclick=()=>openFocus(x.dataset.focus));$$('[data-jump]').forEach(x=>x.onclick=()=>jump(x.dataset.jump));$$('[data-project]').forEach(x=>x.onclick=()=>{state.view='projects';state.activeProject=x.dataset.project;save();render()});$$('[data-person]').forEach(x=>x.onclick=()=>{state.view='people';state.activePerson=x.dataset.person;save();render()});$('[data-back-projects]')?.addEventListener('click',()=>{state.activeProject='';render()});$('[data-back-people]')?.addEventListener('click',()=>{state.activePerson='';render()});$$('[data-day]').forEach(x=>{x.onclick=()=>{state.selectedDate=x.dataset.day;save();render()};x.ondragover=e=>e.preventDefault();x.ondrop=e=>{const id=e.dataTransfer.getData('text/plain');if(id)update(id,{dueDate:x.dataset.day})}});$$('.entity').forEach(x=>{x.draggable=true;x.ondragstart=e=>e.dataTransfer.setData('text/plain',x.id.replace('e-',''))});$$('[data-cal]').forEach(x=>x.onclick=()=>{let d=new Date(state.selectedDate+'T12:00:00');if(x.dataset.cal==='prev')d.setMonth(d.getMonth()-1);if(x.dataset.cal==='next')d.setMonth(d.getMonth()+1);if(x.dataset.cal==='today')d=new Date();state.selectedDate=iso(d);save();render()});$$('[data-add]').forEach(x=>x.onkeydown=e=>{if(e.key==='Enter'){let t=x.value;if(state.view==='calendar')t+=` ${state.selectedDate}`;if(state.view==='people'&&state.activePerson)t+=` @${state.activePerson}`;addItem(t)}});$$('[data-project-add]').forEach(x=>x.onkeydown=e=>{if(e.key==='Enter')addItem(`${x.value} #${x.dataset.projectAdd}`)});$('[data-new-project]')?.addEventListener('click',()=>{const n=prompt('Project name');if(n){state.projects.push({id:uid(),name:n,description:''});save();render()}});$$('[data-action]').forEach(x=>x.onclick=()=>action(x.dataset.action));$$('[data-theme-choice]').forEach(x=>x.onclick=()=>{state.theme=x.dataset.themeChoice;save();render()});$('#palette')?.addEventListener('click',e=>{if(e.target.id==='palette')closePalette()});$('#themeModal')?.addEventListener('click',e=>{if(e.target.id==='themeModal')e.target.classList.remove('open')})}
function action(a){if(a==='palette')openPalette();if(a==='theme')$('#themeModal').classList.add('open');if(a==='timer')toggleTimer();if(a==='focusClose')closeFocus();if(a==='focusDone'&&focus){complete(focus.id);closeFocus()}}
const commands=[['Go to Today',()=>go('today'),'view'],['Open Timeline',()=>go('timeline'),'view'],['Open Calendar',()=>go('calendar'),'view'],['Open Projects',()=>go('projects'),'view'],['Open People',()=>go('people'),'view'],['Archive completed',()=>{active().filter(i=>i.completed).forEach(i=>i.archived=true);save();render()},'action'],['Export data',exportData,'action'],['Import data',importData,'action'],['Storage status',showStorageStatus,'action'],['Change theme',()=>{$('#themeModal').classList.add('open')},'action']];
function go(v){state.view=v;save();render()}
function openPalette(){const p=$('#palette');p.classList.add('open');const q=$('#paletteInput');q.value='';paintPalette('');setTimeout(()=>q.focus(),10);q.oninput=()=>paintPalette(q.value);q.onkeydown=e=>{if(e.key==='Escape')closePalette();if(e.key==='Enter')$('.palette-item')?.click()}}
function closePalette(){$('#palette')?.classList.remove('open')}
function fuzzy(s,q){q=q.toLowerCase();s=s.toLowerCase();let n=0;for(const c of s)if(c===q[n])n++;return n===q.length}
function paintPalette(q){const items=active().filter(i=>!q||fuzzy(`${i.title} ${i.project} ${i.person} ${i.type}`,q)).slice(0,24).map(i=>({kind:i.type,title:i.title,hint:i.dueDate?fmt(i.dueDate):'',run:()=>jump(i.id)}));const cs=commands.filter(c=>!q||fuzzy(c[0],q)).map(c=>({kind:c[2],title:c[0],hint:'',run:c[1]}));const all=[...cs,...items];$('#paletteResults').innerHTML=all.map((x,n)=>`<div class="palette-item ${n===0?'active':''}" data-pi="${n}"><span class="palette-kind">${esc(x.kind)}</span><span>${esc(x.title)}</span><span class="palette-hint">${esc(x.hint)}</span></div>`).join('')||'<div class="empty">No matches.</div>';$$('[data-pi]').forEach(x=>x.onclick=()=>{closePalette();all[+x.dataset.pi].run()})}
function jump(id){const i=state.items.find(x=>x.id===id);if(!i)return;expanded.add(id);state.view=i.type==='note'||i.type==='idea'?'notes':i.dueDate?'timeline':'today';save();render();setTimeout(()=>$('#e-'+id)?.scrollIntoView({behavior:'smooth',block:'center'}),30)}
function openFocus(id){focus=state.items.find(i=>i.id===id);timer=25*60;timerRun=false;clearInterval(timerInt);$('#focusTitle').textContent=focus.title;$('#timer').textContent='25:00';$('#focus').classList.add('open')}
function closeFocus(){clearInterval(timerInt);$('#focus')?.classList.remove('open')}
function toggleTimer(){timerRun=!timerRun;clearInterval(timerInt);if(timerRun)timerInt=setInterval(()=>{timer=Math.max(0,timer-1);const m=Math.floor(timer/60),s=timer%60;$('#timer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');if(!timer){clearInterval(timerInt);toast('Focus complete')}},1000)}
async function showStorageStatus(){const info=await storageInfo();const used=(info.usage/1024/1024).toFixed(2),quota=info.quota?(info.quota/1024/1024).toFixed(0):'?';toast(`IndexedDB · ${used} MB used · ${quota} MB quota${info.persisted?' · persistent':''}`)}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='today-os-m3-data.json';a.click();toast('Exported')}
function importData(){const f=document.createElement('input');f.type='file';f.accept='.json';f.onchange=()=>{const r=new FileReader();r.onload=()=>{try{state={...state,...JSON.parse(r.result)};save();render();toast('Imported')}catch{toast('Invalid file')}};r.readAsText(f.files[0])};f.click()}
let tt;function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('show'),1800)}
document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}else if(e.key==='Escape'){closePalette();closeFocus();$('#themeModal')?.classList.remove('open')}else if(!typing&&e.key==='/'){e.preventDefault();$('#capture')?.focus()}else if(!typing&&e.key.toLowerCase()==='t'){go('today')}else if(!typing&&e.key.toLowerCase()==='f'){const i=active().find(i=>!i.completed&&i.type==='task');if(i)openFocus(i.id)}});
state=await load();await requestPersistentStorage();render();
})();
